name: SDK Compliance Tests

permissions:
  contents: read
  packages: read
  pull-requests: write

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  adapter-tests:
    name: Adapter regression tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdk_compliance_adapter
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          elixir-version: "1.19.5"
          otp-version: "28.3.1"
      - run: mix deps.get
      - run: mix test

  compliance:
    name: PostHog SDK compliance tests
    uses: PostHog/posthog-sdk-test-harness/.github/workflows/test-sdk-action.yml@6d19abb9c81e2262dacbe340e7dddda9c871c178
    with:
      adapter-dockerfile: "sdk_compliance_adapter/Dockerfile"
      adapter-context: "."
      test-harness-version: "1.0.0"
      report-name: "sdk-compliance-elixir-v0-gzip"
